name: ar6-wg3
channels:
  - chrisroadmap
  - conda-forge
dependencies:
  - fair==2.1.3
  - h5py
  - ipython
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pooch
  - python-dotenv
  - scikit-learn
  - scipy
  - tqdm
  - xarray
